# Site settings
author: Chris 
title: "This Is The Way"
header-img: img/home-bg.png
email: thisistheway369@icloud.com
copyright_name: Chris 
description: > # this means to ignore newlines until "baseurl:"
  "LA"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thisistheway369

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
